apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.synctv.envConfigName }}
data:
  DATABASE_TYPE: postgres
  DATABASE_HOST: synctv-postgresql
  DATABASE_PORT: "5432"
  DATABASE_USER: postgres
  DATABASE_NAME: postgres
  SYNCTV_GUARDIAN_REQUIRE_HTTPS: "true"
  SYNCTV_GUARDIAN_TRUST_FORWARDED_PROTO: {{ .Values.synctv.security.trustForwardedProto | quote }}
